[package]
name = "metriki-core"
version = "0.1.2-alpha.0"
authors = ["Ning Sun <sunng@protonmail.com>"]
edition = "2018"
description = "A metrics library ported from dropwizard metrics"
license = "MIT/Apache-2.0"
keywords = ["observability", "metrics", "monitoring"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8"
exponential-decay-histogram = "0.1.9"
